apiVersion: v1
kind: ConfigMap
metadata:
  name: apiadapter-configmap
data:
  RPC_ADDRESS: "http://172.20.185.182:8545"
  ACCOUNT: "0x25211bfc3e3d5cc76f79841a0d43dd180c0ee5a7"
  SMARTCONTRACT_ENDPOINT: "http://172.20.1.86:5000"


---

apiVersion: v1

kind: Pod

metadata:
  name: apiadapter
  labels:
    app: apiadapter

spec:
  containers:
    - name: apiadapter-container
      image: mabdockerid/apiadapter:latest
      env:
      # cluster ip on the Qourum Node 2
        - name: RPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: RPC_ADDRESS
        - name: ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: ACCOUNT
      # smart contract endpoint. will use /contractAddress and /abi to update the configuration of the API Adapter.
      # It will override the env. CONTRACT_ADDRESS value if set.
        - name : SMARTCONTRACT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: SMARTCONTRACT_ENDPOINT
      ports:
        - containerPort: 3000
      imagePullPolicy: Always


---


apiVersion: v1
kind: Service
metadata:
  name: apiadapter-service
  labels:
    name: apiadapter-service

spec:
  selector:
    app: apiadapter

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer


